name: github pages

on:
  push:
    paths:
     - BivariateRenderer/metadata.txt
     - .github/workflows/mkdocs_build_deploy.yaml

jobs:

  call-workflow-mkdocs:
    uses: JanCaha/github_workflows/.github/workflows/run_deploy_mkdocs.yaml@8db0e6e005750801f1a6c0f767e7a635a34596fa
    with:
      deploy_repo: $GITHUB_REPOSITORY
      mkdocs_config_location: ./website/mkdocs.yml
      nojekyll_location: ./website/docs/.nojekyll
    secrets:
      auth_token: ${{ secrets.REPO_ACCESS }}
