name: github pages

on:
  push:
    paths:
     - BivariateRenderer/metadata.txt
     - .github/workflows/mkdocs_build_deploy.yaml

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2.3.4

  call-workflow-mkdocs:
    uses: JanCaha/github_workflows/.github/workflows/run_deploy_mkdocs.yaml
    with:
      mkdocs_config_location: ./website/mkdocs.yml
      nojekyll_location: ./website/docs/.nojekyll
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
