name: github pages

on:
  push:
    paths:
     - BivariateRenderer/metadata.txt
     - .github/workflows/mkdocs_build_deploy.yaml

jobs:

  echo:

    name: Print variable

    runs-on: ubuntu-latest

    steps:

      - name: Echo
        run: echo "${{ github.event.owner.login }}/${{ github.event.repository.name }}"

      - name: Echo
        run: echo "$ {{ github.event.actor.login }}"

      - name: Echo
        run: echo "$ {{ github.event.actor.display_login }}"

      - name: Echo
        run: echo "$ {{ github.event.repo }}"

      - name: Echo
        run: echo "$ {{ github.event.repo.id }}"

      - name: Echo
        run: echo "$ {{ github.event.repo.url }}"


#  call-workflow-mkdocs:
#    uses: JanCaha/github_workflows/.github/workflows/run_deploy_mkdocs.yaml@e25d2e605b137e8946c06770fcaf6609ba3c0789
#    with:
#      deploy_repo: ${{ github.event.actor.login }}/${{ github.event.repository.name }}
#      mkdocs_config_location: ./website/mkdocs.yml
#      nojekyll_location: ./website/docs/.nojekyll
#    secrets:
#      auth_token: ${{ secrets.REPO_ACCESS }}
