name: github pages

on:
  push:
    paths:
     - BivariateRenderer/metadata.txt
     - .github/workflows/mkdocs_build_deploy.yaml

jobs:

  call-workflow-mkdocs:
    uses: JanCaha/github_workflows/.github/workflows/run_deploy_mkdocs.yaml@e25d2e605b137e8946c06770fcaf6609ba3c0789
    with:
      mkdocs_config_location: ./website/mkdocs.yml
      nojekyll_location: ./website/docs/.nojekyll
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
