name: github pages

on:
  push:
    paths: BivariateRenderer/metadata.txt

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install mkdocs
        python3 -m pip install MarkdownHighlight
        python3 -m pip install https://codeload.github.com/mkdocs/mkdocs-bootstrap/zip/master

    - name: Build
      run: |
        mkdocs build --config-file ./website/mkdocs.yml
        touch website/docs/.nojekyll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./website/docs