name: github pages

on:
  push:
    paths:
     - BivariateRenderer/metadata.txt
     - .github/workflows/mkdocs_build_deploy.yaml

jobs:

  call-workflow-mkdocs:
    uses: JanCaha/github_workflows/.github/workflows/run_deploy_mkdocs.yaml@fe4b2c81e28815b61113d344e3b841e28c75b1c8
    with:
      mkdocs_config_location: ./website/mkdocs.yml
      nojekyll_location: ./website/docs/.nojekyll
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
