name: Generate Tests Graphical Results for Plugin BivariateRenderer

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: workflow_dispatch

env:
  DEBIAN_FRONTEND: noninteractive
  QT_QPA_PLATFORM: offscreen
  XDG_RUNTIME_DIR: /tmp
  BIVARIATE_GENERATE: true

jobs:
  Generate-Tests-Graphical-Results-for-plugin-BivariateRenderer:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          use-mamba: true
          channels: conda-forge,defaults
          auto-activate-base: true
          activate-environment: ""

      - name: Install conda-build
        run: |
          conda install -n base pip qgis pytest pytest-cov pillow pytest-qt
          conda run -n base pip install --no-cache-dir pytest-qgis pixelmatch

      - name: Run tests
        run: |
          conda run -n base pytest tests/tests_visual_result_generation -rP -vv -s

      - name: Commit and push graphical test results
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tests/images/correct/*
          git commit -m "Update graphical test results [CI skip]" || echo "No changes to commit"
          git push
