name: Tests for Plugin BivariateRenderer

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "BivariateRenderer/**"
      - "tests/**"
      - ".github/workflows/test_plugin.yaml"
  workflow_dispatch:

env:
  CONDA_PKGS_DIRS: ~/conda_pkgs_dir
  DEBIAN_FRONTEND: noninteractive
  QT_QPA_PLATFORM: offscreen
  XDG_RUNTIME_DIR: /tmp
  PYTHONPATH: ./qgis-plugin-bivariate-renderer
  QT_SCALE_FACTOR: 1
  QT_AUTO_SCREEN_SCALE_FACTOR: 0
  QT_FONT_DPI: 96

jobs:
  Tests-plugin-BivariateRenderer:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        qgis-version: ["3.40", "3.42", "3.44"]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache conda packages
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: conda-pkgs-${{ runner.os }}-${{ matrix.qgis-version }}

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          use-mamba: true
          channels: conda-forge,defaults

      - name: Create environment
        run: conda create -n qgis_env --no-default-packages --yes

      - name: Install QGIS and test dependencies
        run: |
          conda install -n qgis_env qgis=${{ matrix.qgis-version }} pytest pytest-cov pillow pytest-qt --yes
          conda run -n qgis_env pip install --no-cache-dir pytest-qgis pixelmatch

      - name: Run tests
        run: |
          conda run -n qgis_env pytest tests --cov=BivariateRenderer --cov-report=term-missing:skip-covered -rP -vv -s --ignore=tests/tests_visual_result_generation

      - name: Upload Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: warn
          name: artifacts-qgis-${{ matrix.qgis-version }}
          path: /tmp/images_diff
