name: Tests for Plugin BivariateRenderer

on:
  push:
    paths:
      - "BivariateRenderer/**"
      - "tests/**"
      - ".github/workflows/test_plugin.yaml"

env:
  DEBIAN_FRONTEND: noninteractive
  QT_QPA_PLATFORM: offscreen
  XDG_RUNTIME_DIR: /tmp
  PYTHONPATH: /usr/share/qgis/python/plugins:/usr/share/qgis/python:./qgis-plugin-bivariate-renderer

jobs:
  Tests-plugin-BivariateRenderer:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          use-mamba: true
          channels: conda-forge,defaults
          auto-activate-base: true
          activate-environment: ""

      - name: Install conda-build
        run: |
          conda install -n base pip qgis pytest pytest-cov pillow pytest-qt
          conda run -n base pip install --no-cache-dir pytest-qgis pixelmatch

      - name: Run tests
        run: |
          conda run -n base pytest tests --cov=BivariateRenderer --cov-report=term-missing:skip-covered -rP -vv -s --ignore=tests/tests_visual_result_generation

      - name: Upload Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: warn
          name: artifacts
          path: /tmp/images_diff
